rememberly/moments/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
#from django.contrib.auth.views import login, logout

urlpatterns = patterns('moments.views',
    url(r'^$', 'feed', name='moments_index'),
    url(r'^random/$', 'randompage', name='moments_random'),

    url(r'^ask/$', 'ask', name='moments_ask'),
    url(r'edit/q/(?P<id>\d+)/$', 'edit_question', name='moments_edit_question'),
    url(r'delete/q/(?P<id>\d+)/$', 'delete_question', name='moments_delete_question'),

    url(r'tag_friend/a/(?P<id>\d+)/$', 'tag_friend', name='moments_tag_friend'),
    url(r'respond/q/(?P<id>\d+)/$', 'respond', name='moments_respond'),
    url(r'edit/a/(?P<id>\d+)/$', 'edit_answer', name='moments_edit_answer'),
    url(r'delete/a/(?P<id>\d+)/$', 'delete_answer', name='moments_delete_answer'),

    url(r'a/(?P<id>\d+)/$', 'answer', name='moments_answer'),
	url(r'(?P<id>\d+)/$', 'question', name='moments_question'), #(?P<slug>[-w]+)/

)

rememberly/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('rememberly',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    
    # AUTH
    (r'^accounts/', include('registration.urls')),
    (r'^facebook/', include('django_facebook.urls')),	

	# EXTERNAL APPS
	(r'^tinymce/', include('tinymce.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    
	# INTERNAL APPS
	(r'^moments/', include('moments.urls')),   	
    (r'^profiles/', include('profiles.urls')),   

    url(r'^magicword/(?P<key>\w+)/$', 'views.magicword', name='magicword'),	  	
    url(r'delete/c/(?P<answer_id>\d+)/(?P<comment_id>\d+)/$', 'views.delete_own_comment', name='delete_own_comment'),
    url(r'^$', 'views.home', name='home'),

    url(r'^(?P<username>\w+)/$', 'profiles.views.profile_detail', name='profile_detail'),	  	
)

urlpatterns += staticfiles_urlpatterns()

rememberly/moments/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse

class Question(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length = 300)
	slug = models.SlugField()
	description = models.TextField(blank=True,null=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	deleted = models.BooleanField(default=False)
	is_open = models.BooleanField(default = True)
	answer_count = models.PositiveIntegerField(default = 0)

	@models.permalink
	def get_absolute_url(self):
		return ('moments_question', [str(self.id)]) #, self.slug

	def save(self):
		self.slug = slugify(self.title)[:50]
		super(Question, self).save()

	def delete(self):
		self.deleted = True
		self.save()
				
	def __str__(self):
		return self.title 
	
	class Admin:
		pass

class Answer(models.Model):
	user = models.ForeignKey(User)
	question = models.ForeignKey(Question)
	text = models.TextField()
 	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	deleted = models.BooleanField(default=False)
	friends = models.ManyToManyField(User, through='AnswerFriend', related_name = 'friends')

	@models.permalink
	def get_absolute_url(self):
		return ('moments_answer', [self.id])
		
	def save(self):
		self.slug = slugify(self.text)[:50]
		super(Answer, self).save()
	
	def delete(self):
		self.deleted = True
		self.save()
			
	def __str__(self):
		return self.text    

	class Admin:
		pass

class AnswerFriend(models.Model):
	friend = models.ForeignKey(User, related_name = 'friend', blank=True, null=True, default=None)
	facebook_id = models.BigIntegerField(blank=True, null=True, default=None)
	answer = models.ForeignKey(Answer)	
	question = models.ForeignKey(Question)
 	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	deleted = models.BooleanField(default=False)

	class Admin:
		pass

	def __str__(self):
		return str(self.facebook_id)

rememberly/moments/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

import random, logging

from moments.models import *
from django.db.models import F
from moments import aforms
from django_facebook.models import FacebookUser
from profiles.models import UserProfile

from itertools import chain
from operator import attrgetter

def feed(request):
    qform = aforms.QuestionForm()
    payload = {'qform' : qform}
    return render(request, 'moments/feed.html', payload)
    
@login_required
def ask(request):
    """Ask a question"""
    if request.method == 'POST':
        qform = aforms.QuestionForm(request.user, request.POST)
        if qform.is_valid():
            question = qform.save()
            return HttpResponseRedirect(question.get_absolute_url())
    elif request.method == 'GET':
        qform = aforms.QuestionForm()
    payload = {'qform':qform}
    return render_to_response('moments/ask.html', payload, RequestContext(request))


@login_required
def edit_question(request, id):
	q = Question.objects.get(pk = id)
	if request.method == 'POST' and q.user == request.user:
		qform = aforms.QuestionForm(data=request.POST, instance=q) 
		if qform.is_valid():
			if(qform.save()):
				return HttpResponseRedirect(q.get_absolute_url())
	else:
		qform = aforms.QuestionForm(instance=q) 
	payload = {'question':q, 'qform':qform, }
	return render_to_response('moments/edit/question.html', payload, RequestContext(request))
	
@login_required
def delete_question(request, id):
	q = Question.objects.get(pk = id)
	if q.user == request.user:
		q.delete()
	return HttpResponseRedirect(reverse('moments_index'))

@login_required
def question(request, id):
    """Question Page with Answers to question with the given id"""
    q = Question.objects.get(pk = id)
    a = q.answer_set.filter(deleted = False).order_by('-created')[:20]
    if request.method == 'GET':
        aform = aforms.AnswerForm()
    payload = {'question':q, 'answers':a, 'aform':aform, }
    return render_to_response('moments/question.html', payload, RequestContext(request))
    	
@login_required
def respond(request, id):
	q = Question.objects.get(pk = id)
	if request.method == 'POST':
		aform = aforms.AnswerForm(user = request.user, question = q, data = request.POST)
		if aform.is_valid():
			if(aform.save()):
				q.answer_count = F('answer_count') + 1
				q.save()
	return HttpResponseRedirect(q.get_absolute_url())

@login_required
def edit_answer(request, id):
	a = Answer.objects.get(pk = id)
	q = a.question
	if request.method == 'POST' and a.user == request.user:
		aform = aforms.AnswerForm(data=request.POST, instance=a) 
		if aform.is_valid():
			if(aform.save()):
				return HttpResponseRedirect(a.get_absolute_url())
	else:
		aform = aforms.AnswerForm(instance=a) 
	payload = {'question':q, 'answers':a, 'aform':aform, }
	return render_to_response('moments/edit/answer.html', payload, RequestContext(request))

@login_required
def delete_answer(request, id):
	a = Answer.objects.get(pk = id)
	if a.user == request.user:
		a.delete()
	return HttpResponseRedirect(reverse('moments_index'))
		
@login_required
def answer(request, id):
    """Answer Page"""
    a = Answer.objects.get(pk = id)
    q = a.question
    if( False and a.user == request.user ):
        fb_friends = random_fb_friends(request.user.id)
    else:
        fb_friends = None
    payload = {'question':q, 'answer':a, 'fb_friends': fb_friends }
    return render_to_response('moments/answer.html', payload, RequestContext(request))
    
@login_required
def tag_friend(request, id):
	if request.method == 'POST':
		af_form = aforms.AnswerFriendForm(request.POST)
		af = af_form.save(commit=False)
		af.answer = Answer.objects.get(pk = request.POST['answer_id'])
		af.question = af.answer.question
		af.facebook_id = request.POST['facebook_id']
		try:
			af.friend = UserProfile.objects.get(facebook_id = af.facebook_id).user
		except UserProfile.DoesNotExist:
			af.friend = None	
		
		af.save()
	return HttpResponseRedirect(af.answer.get_absolute_url())

def randompage(request):
    for i in xrange(5):
        i = Question.objects.filter(deleted = False).count()
        randcount = random.randint(1, i - 1)
        question = Question.objects.get(id = randcount)
        if question.is_open:
            return HttpResponseRedirect(question.get_absolute_url())
    return HttpResponseRedirect(question.get_absolute_url())
    
def render(request, template, payload):
    open_questions = Question.objects.filter(is_open = True, deleted = False)[:20]
    recently_answered = Answer.objects.filter(deleted = False).order_by('-created')[:20]
   
    items = sorted(chain(open_questions, recently_answered),key=attrgetter('created'), reverse=True)
    
    payload.update({'items': items,})
    return render_to_response(template, payload, RequestContext(request))

def random_fb_friends(id):
	count = FacebookUser.objects.filter(user_id = id).count()
	slice = random.random() * (count - 10)
	return FacebookUser.objects.filter(user_id = id)[slice: slice+10]
   
    

rememberly/moments/templates/moments/add_topic.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action=".">
    {{form.as_p}}
    <input type="submit" value="Add Category" name=ask"" />
</for>
{% endblock %}

rememberly/moments/templates/moments/answer.html
{% extends 'base.html' %}
{% block content %}
{% load comments %}
<div id="answer-page">
	
	<div class="question page-header">
		<div class="question-info">
			<h2>
				<a class="question-title" href="{{ question.get_absolute_url }}">{{ question.title}}</a>
			</h2>
		</div>
	</div>
	
	<ul class="answers unstyled">
		{% include 'moments/answer/_answer.html' %}
	</ul>
	<div class="answer-comments">
		{% render_comment_list for answer %}
	</div>
	<div class="comment-form row">
		<div class="offset1 span14">
			{% render_comment_form for answer %}
		</div>
	</div>
		
	{% for fb_friend in fb_friends %}
		<div class="fb_friend">
		    <p>
		    	<img src="https://graph.facebook.com/{{fb_friend.facebook_id}}/picture"/>
		        <span>{{fb_friend.name}}</span>
	        	<form method="post" action="{% url moments_tag_friend answer.id %}" class="form-stacked">
					{% csrf_token %}
				    <input type="hidden" name="answer_id" id="id_answer" value="{{answer.id}}" />
				    <input type="hidden" name="facebook_id" id="id_facebook" value="{{fb_friend.facebook_id}}" />
				    <input type="submit" value="Tag" name="tag_friend" class="btn"/>
				</form>
		    </p>	
		</div>
	{% endfor %}
</div>
{% endblock %}

rememberly/moments/templates/moments/ask.html
{% extends 'base.html' %}

{% block content %}

<div id="ask_moment" class="ask">
	{% include "moments/ask_form.html" %}
</div>

{% endblock %}

rememberly/moments/templates/moments/ask_form.html
<div class="alert-message block-message info">
	<form method="post" action="{% url moments_ask %}" class="form-stacked">
		{% csrf_token %}
		{% if qform.title.errors %}
			<div class="alert-message error">{{ qform.title.errors }}</div>
		{% endif %}
		<label for="id_title" ><span class="circle">1</span> Start by asking about a moment or event in question form <span class="circle">2</span>  Answer it with your story <span class="circle">3</span>  Read other peoples responses</label>
		{{ qform.title}}
		<input type="submit" value="Ask" name=ask""  class="btn primary"/>
	</form>
</div>

rememberly/moments/templates/moments/feed.html
{% extends 'base.html' %}

{% block content %}

<div id="intro_blurb">
    <p>Rememberly is a place to <strong>share the memorable stories of your life</strong> with the world</p>
</div>
<div id="moments_ask" class="ask">
    {% if user.is_authenticated %}
		{% include "moments/ask_form.html" %}
    {% else %}
        <div class="alert-message block-message warning">
           <a href="{% url auth_login %}">Login</a> to ask questions
        </div>
    {% endif %}
</div>

<!--
<div id="feed_nav" class="row">
	<div class="span10">
		<ul class="pills" data-tabs="pills">
			<li class="active"><a href="#feed">Feed</a></li>
		  	<li><a href="#recent">Recent</a></li>		
		  	<li><a href="#open">Open</a></li>		
		</ul>       
	</div>
</div>
-->
<div id="moment_feed" class="row feed">
	<div class="span14">
		<div class="">
			<div id="feed" class="active">
				{% if items.count > 0 %}
				  <ul class="unstyled">
				  {% for item in items %}
				  	
				  	{% if item.text %}
				  		{% include "moments/feed/_answer.html" %}
			  		{% endif %}
			  		
				  	{% if item.title %}
				  		{% include "moments/feed/_question.html" %}
				  	{% endif %}
				  	
				  {% endfor %}
				  </ul>
				{% else %}
					<p>No activity yet</p>
				{% endif %}
			</div>		
	 	</div>	
	</div>
</div>

{% endblock %}

rememberly/moments/templates/moments/question.html
{% extends 'base.html' %}

{% block content %}

<div class="question page-header">
	<div class="question-info">
		<h2>{{question.title}}</h2>
		<div class="question-description">
			{% if  question.description %}
				<p>{{question.description}}</p>
			{% endif %}	
		</div>	
		<div class="question-details">
		    Asked by <a href="{% url profile_detail question.user.username %}">{{question.user.first_name}} {{question.user.last_name}}</a>
		    on <a href="{{ question.get_absolute_url }}">{{question.created|date}}</a>
			{% if question.user = user %}
				<span class="bullet">&bull;</span>
				<a class="edit-link" href="{% url moments_edit_question question.id %}">Edit</a>
				<span class="bullet">&bull;</span>
				<a class="delete-link" href="{% url moments_delete_question question.id %}">Hide</a>
			{% endif %}		    
		</div>
	</div>

	<div id="question-respond" class="respond row">
		<div class="span1">
  			<a class="respond-image" href="{% url profile_detail user.username %}">
  				<img src="https://graph.facebook.com/{{ user.userprofile.facebook_id}}/picture"/>
  			</a>			
		</div>
		<div class="span8">
			<form method="post" action="{% url moments_respond question.id %}" class="form-stacked">
				{% csrf_token %}
				{{ aform.title.errors }}
				<div class="clearfix">
					{{ aform.text}}
				</div>
				<div class="clearfix">
				    <input type="submit" value="Answer" name="ask" class="btn primary"/>
				</div>
			</form>
		</div>
	</div>
</div>


<ul class="answers unstyled">
{% if answers.count > 0 %}
	{% for answer in answers %}
		{% include 'moments/question/_answer.html' %}
	{% endfor %}
{% else %}
	{{ user.first_name }}, be the first to share your story about this moment!
{% endif %}
</ul>

{% endblock %}