fashionista/socialgraph/urls.py
from django.conf.urls.defaults import *
from fashionista.socialgraph import views

urlpatterns = patterns('',
    url(
        r'^followers/(?P<username>[a-zA-Z0-9_-]+)/$',
        views.friend_list,
        {'list_type': 'followers'},
        name='sg_followers'
    ),
    url(
        r'^following/(?P<username>[a-zA-Z0-9_-]+)/$',
        views.friend_list,
        {'list_type': 'following'},
        name='sg_following'
    ),
    url(
        r'^mutual/(?P<username>[a-zA-Z0-9_-]+)/$',
        views.friend_list,
        {'list_type': 'mutual'},
        name='sg_mutual'
    ),
    url(
        r'^follow/(?P<username>[a-zA-Z0-9_-]+)/$',
        views.follow,
        name='sg_follow'
    ),
    url(
        r'^unfollow/(?P<username>[a-zA-Z0-9_-]+)/$',
        views.unfollow,
        name='sg_unfollow'
    ),
    url(
        r'^search/$',
        views.find_and_add,
        name='sg_find_add'
    ),
)

fashionista/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic.list_detail import object_list

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    # Example:
    # (r'^fashionista/', include('fashionista.foo.urls')),
    (r'^', include('fashionista.gallery.urls')),
	(r'^services/', include('fashionista.socialregistration.urls')),
    (r'^cocos/', include('fashionista.socialgraph.urls')),
    (r'^profile/', include('fashionista.profile.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    url(r'^settings/$', 'fashionista.profile.views.edit', name='settings'),
    url(r'^cocos/latest/$',
        login_required(object_list),
        {'queryset': User.objects.order_by('-date_joined'),
        'paginate_by': 50, 'allow_empty': True},
        name='user_list'),
    url(r'^about/$', 'django.views.generic.simple.direct_to_template', 
        {'template': 'misc/about.html'}, name='about'),
)

fashionista/socialgraph/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

class UserLink(models.Model):
    """
    A single directed edge in the social graph.  Usually represented as the
    verb "follows".
    """
    from_user = models.ForeignKey(User, related_name='following_set')
    to_user = models.ForeignKey(User, related_name='follower_set')
    date_added = models.DateTimeField(default=datetime.now)

    def __unicode__(self):
        return "%s is following %s" % (self.from_user.username, 
            self.to_user.username)

    def save(self, **kwargs):
        """
        A mostly-generic save method, except that it validates that the user
        is not attempting to follow themselves.
        """
        if self.from_user == self.to_user:
            raise ValueError("Cannot follow yourself.")
        super(UserLink, self).save(**kwargs)
    
    class Meta:
        unique_together = (('to_user', 'from_user'),)

fashionista/socialgraph/forms.py
from django import forms

class SearchForm(forms.Form):
    """
    A simple search form with a query input.
    """
    q = forms.CharField(max_length=50)

fashionista/socialgraph/views.py
from django.utils.translation import ugettext as _
from django.shortcuts import render_to_response, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from fashionista.socialgraph.models import UserLink
from fashionista.socialgraph.util import get_people_user_follows, get_people_following_user
from fashionista.socialgraph.util import get_mutual_followers
from fashionista.socialgraph.forms import SearchForm

def _get_next(request):
    """
    1. If there is a variable named ``next`` in the *POST* parameters, the view will
    redirect to that variable's value.
    2. If there is a variable named ``next`` in the *GET* parameters, the view will
    redirect to that variable's value.
    3. If Django can determine the previous page from the HTTP headers, the view will
    redirect to that previous page.
    """
    return request.POST.get('next', request.GET.get('next', request.META.get('HTTP_REFERER', None)))

FRIEND_FUNCTION_MAP = {
    'followers': get_people_user_follows,
    'following': get_people_following_user,
    'mutual': get_mutual_followers,
}

def friend_list(request, list_type, username):
    """
    Renders a list of friends, as returned by the function retrieved from the
    ``FRIEND_FUNCTION_MAP``, given the user specified by the username in the
    URL.
    """
    user = get_object_or_404(User, username=username)
    context = {
        'list_type': list_type,
        'friends': FRIEND_FUNCTION_MAP[list_type](user),
    }
    return render_to_response(
        'friend_list.html',
        context,
        context_instance = RequestContext(request)
    )

def follow(request, username):
    """
    Adds a "following" edge from the authenticated user to the user specified by
    the username in the URL.
    """
    user = get_object_or_404(User, username=username)
    ul, created = UserLink.objects.get_or_create(from_user=request.user, 
        to_user=user)
    next = _get_next(request)
    if next and next != request.path:
        request.user.message_set.create(
            message=_('You are now following %s') % user.username)
        return HttpResponseRedirect(next)
    context = {
        'other_user': user,
        'created': created,
    }
    return render_to_response(
        'followed.html',
        context,
        context_instance = RequestContext(request)
    )
follow = login_required(follow)

def unfollow(request, username):
    """
    Removes a "following" edge from the authenticated user to the user specified
    by the username in the URL.
    """
    user = get_object_or_404(User, username=username)
    try:
        ul = UserLink.objects.get(from_user=request.user, to_user=user)
        ul.delete()
        deleted = True
    except UserLink.DoesNotExist:
        deleted = False
    next = _get_next(request)
    if next and next != request.path:
        request.user.message_set.create(
            message=_('You are no longer following %s') % user.username)
        return HttpResponseRedirect(next)
    context = {
        'other_user': user,
        'deleted': deleted,
    }
    return render_to_response(
        'unfollowed.html',
        context,
        context_instance = RequestContext(request)
    )
unfollow = login_required(unfollow)

def find_and_add(request):
    """
    A page for finding and adding new friends to follow.  Right now this
    consists solely of a search box, which given input, renders a list of
    users who match the search terms.
    """
    search_form = SearchForm(request.GET or None)
    context = {
        'search_form': search_form,
    }
    if search_form.is_valid():
        q = search_form.cleaned_data['q']
        context['q'] = q
        users = User.objects.filter(username__icontains=q) | User.objects.filter(
            email__icontains=q)
    else:
        users = []
    friends = get_people_user_follows(request.user)
    users = [(u, u in friends) for u in users]
    context['users'] = users
    context['user_count'] = len(users)
    return render_to_response(
        'find_add.html',
        context,
        context_instance = RequestContext(request)
    )
find_and_add = login_required(find_and_add)

fashionista/socialgraph/templates/find_add.html
{% extends "base.html" %}
{% load profile_tags %}

{% block title %}Find and Add Friends - {{ block.super }}{% endblock %}

{% block main_content %}
    <form class="standard" method="GET">
        <ul>
            <li><label for="id_q">Search for your friend&rsquo;s name or e-mail address: </label>
                {{ search_form.q }}</li>
        </ul>
        <input type="submit" value="User Search">
    </form>
    {% if q %}
        <h1>Results</h1>
        {% ifequal user_count 0 %}
            <p class="info">No results for the given query</p>
        {% else %}
            {% for person, friend in users %}
                <div class="follow">
                    {% person person %}
                    {% ifnotequal person user %}
                        <form method="POST" action="{% if friend %}{% url sg_unfollow person.username %}{% else %}{% url sg_follow person.username %}{% endif %}">
                            <input type="submit" value="{% if friend %}Unfollow{% else %}Follow{% endif %}" />
                        </form>
                    {% endifnotequal %}
                </div>
            {% endfor %}
        {% endifequal %}
    {% endif %}
    <p class="info">Don&rsquo;t see any people you know?  Check out the <a href="{% url user_list %}">list of newest users</a> to see if you know anyone there.</p>
{% endblock %}

fashionista/socialgraph/templates/friend_list.html
{% extends "base.html" %}
{% load profile_tags %}

{% block title %}Friend List - {{ block.super }}{% endblock %}

{% block main_content %}
    {% ifequal list_type "followers" %}
        <h1>People Who You Follow:</h1>
    {% else %}
        {% ifequal list_type "following" %}
            <h1>People Following You:</h1>
        {% else %}
            <h1>People Who You Follow, Who Also Follow You:</h1>
        {% endifequal %}
    {% endifequal %}
    {% ifequal friends.count 0 %}
        <p class="info">No friends listed</p>
    {% else %}
        {% for friend in friends %}
            {% person friend %}
        {% endfor %}
    {% endifequal %}
{% endblock %}